Полная проверка дз
Garedbang/adidas-shop-frontend pull request #1
Opened 2017-05-13 07:52 UTC by Garedbang

Перевел первую страницу в реакт компоненты, сделал стили через styled-components.

Шрифты подключены через цсс, пока не трогал их. так же есть папка images - она старая.

2017-05-13 10:15 UTC, imevro requested changes
1) вытащи компоненты из рендера и функций
2) что за нормалайзер? Мб normalize.css?
3) ФОРМАТИРОВАНИЕ — ПОСТАВЬ ПРЕТТИР

http://telegra.ph/6a640335-fcfd-4e53-b0d9-25cd145cb565-05-12
про структуру
почему сетку нельзя засовывать в карточку
правила импортов

2017-05-13 10:15 UTC, evgenyrodionov commented on src/App.css
> +ul, li {
Нельзя

2017-05-13 10:15 UTC, evgenyrodionov commented on src/App.css
> +button {
Нельзя

2017-05-13 10:15 UTC, evgenyrodionov commented on src/App.css
> +a {
Нельзя

2017-05-13 10:15 UTC, evgenyrodionov commented on src/App.css
> +section {
Нельзя

2017-05-13 10:15 UTC, evgenyrodionov commented on src/App.css
> +  -webkit-box-flex: 2;
В create-react-app есть автопрефиксер, можно опустить тут ручное указание их

2017-05-13 10:15 UTC, evgenyrodionov commented on src/App.js
> +import normalizer from 'normalizer';
Что это

2017-05-13 10:15 UTC, evgenyrodionov commented on src/App.js
> +    const Wrapper = styled.main`
За пределы рендера

2017-05-13 10:15 UTC, evgenyrodionov commented on src/ContentSection/Header/index.js
> +  const Header = styled.header`
За пределы функции

2017-05-13 10:15 UTC, evgenyrodionov commented on src/ContentSection/ProductCard/index.js
> +// export default () => {
Это что?

2017-05-13 12:14 UTC, Garedbang commented on src/ContentSection/ProductCard/index.js
> +// export default () => {
мусор, я пытался в самом начале сделать переиспользуемую карточку для товара, но забил

2017-05-14 00:01 UTC, Garedbang commented
Добавил 2 страницу, добавил роутер.
Не исправил проблему с Sale.
Задеплоил на surge.

2017-05-14 10:02 UTC, imevro requested changes
Пофикси еслинт

2017-05-14 14:10 UTC, imevro requested changes
Фикси

2017-05-14 14:10 UTC, evgenyrodionov commented on src/ProductsSection/List/Filters/index.jsx
> +&:hover {
Чё с отступами

2017-05-14 14:10 UTC, evgenyrodionov commented on src/index.html
> +<!DOCTYPE html>
Этот файл нахуя тут

2017-05-14 14:10 UTC, evgenyrodionov commented on src/Sidebar/index.jsx
> +    <ProductsList />
Как продакстлист оказался в сайдбаре?

2017-05-14 14:10 UTC, evgenyrodionov commented on src/index.js
> +import './Fonts.css';
Фонтс это не компонент, поэтому с маленькой буквы

2017-05-14 18:17 UTC, imevro requested changes
Переделывай архитектуру

2017-05-14 18:17 UTC, evgenyrodionov commented on src/ProductsSection/List/Filters/index.jsx
> +      <Span>
как в спане могут быть блочные элементы

2017-05-14 18:17 UTC, evgenyrodionov commented on src/ProductsSection/List/Filters/index.jsx
> +        <Button firstChildPadding type="button">36</Button>
тупой проп, лучше используй :first-child из цсс, а лучше вообще обойдись без этой хуйни

2017-05-14 18:17 UTC, evgenyrodionov commented on src/ProductsSection/List/ProductCard/index.jsx
> +    <ProductLink active to="/product">$1024</ProductLink>
зачем префикс продакт

2017-05-14 18:17 UTC, evgenyrodionov commented on src/ProductsSection/List/Products/index.jsx
> +import ProductCard from '../ProductCard';
зачем префикс продакт

2017-05-15 08:53 UTC, closed without merging